public enum SoundType
{
    BACKGROUND_MUSIC,
    BUTTON_CLICK,
    BUTTON_QUIT,
    COLLECTIBLE_PICKUP,
    GAME_PAUSE,
    GAME_OVER,
    GAME_PLAY,
    PLAYER_JUMP,
    PLAYER_AIR_JUMP,
    PLAYER_SLIDE,
    PLAYER_KNOCKBACK,
    PLAYER_DEAD
}